### ISSUE TITLE
Implement welcome-page 

### ISSUE THREAD

**Issue by Daki404** [Daki404/Beaten_beat#1]
## Description
welcome-page를 구현 합니다.  
Beaten-beat에 대한 설명을 간단하게 합니다.  
Drawer로 기능 목록을 열 수 있습니다.

## Todo
- [x] welcome-page 들어갈 내용 정리하기 
- [x] hero-banner 만들기
- [x] intro-player 만들기
- [x] detail-explain 만들기
- [x] footer 만들기
