### ISSUE TITLE
Implement login & account-page

### ISSUE THREAD

**Issue by Daki404** [Daki404/Beaten_beat#2]
## Description
글로벌 네이게이션 바에, accout-page를 만듭니다.
로그인을 하지 않았을 때는 login이 나오고,
이를 클릭하면 나오는 login 화면을 추가 합니다.

## Todo
- [ ] login 안 했을 때,  GNB 변경
- [ ] login 화면 구현(redirection)
  - [ ]  google 로그인
  - [ ]  kakao 로그인
  - [ ]  naver 로그인
- [ ] account-page 구현
